# build
FROM golang:1.12.1-stretch AS build
WORKDIR /go/src/${owner:-github.com/IzakMarais}/reporter
RUN apt-get update && apt-get install -y make git
RUN git clone https://${owner:-github.com/IzakMarais}/reporter .
RUN make build


# create image
FROM debian:stretch
COPY  install-tl-unx.tar.gz  .
RUN PACKAGES="wget libswitch-perl" \
    && apt-get update \
    && apt-get install -y -qq $PACKAGES --no-install-recommends \
    && tar xzvf install-tl-unx.tar.gz \
    && cd install-tl-* \
    && ./install-tl -profile /texlive.profile \
    # Cleanup
    && rm -rf install-tl-* \
    && apt-get remove --purge -y -qq $PACKAGES \
    && apt-get autoremove --purge -y -qq \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /var/tex

COPY --from=build /go/bin/grafana-reporter /usr/local/bin
ENTRYPOINT [ "/usr/local/bin/grafana-reporter","-ip","jmeter-grafana:3000" ]
